# -*- coding: utf-8 -*-
"""line_bot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GNG3eVHQO4TzAV-YygIss_6pCU46rmO5
"""

from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextSendMessage, TextMessage
import pya3rt

app = Flask(__name__)

line_bot_api = LineBotApi('zNX+V0h6Kd2vZQlmkkqwkgFDV+RmTgWo9Rpy3szssl4l1fCejpic2koDi+HlBC5n6dlpsGc8HQFdGjIWQ7co92TLRkhehFU8+K3VfAQg4FkcRxPxCsOhcM/DbGk+OMQZ4EEvWNE468Oo36U91+q43QdB04t89/1O/w1cDnyilFU=')
handler = WebhookHandler('92e70f7f052ae1d83c9709b727d3fc9d')

@app.route('/callback', methods=['POST'])
def callback():
  signature = request.headers['X-Line-Signature']
  body = request.get_data(as_text=True)

  try:
    handler.handle(body,signature)
  except InvalidSignatureError:
    abort(400)
  
  return "OK"

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
  ai_message = talk_ai(event.message.text)
  line_bot_api.reply_message(event.reply_token, TextSendMessage(text=ai_message))

def talk_ai(word):
  apikey = "DZZGpM8TQzaJZuqw0YPfTgpWonHZ8lTq"
  client = pya3rt.TalkClient(apikey)
  reply_message = client.talk(word)
  return reply_message['results'][0]['reply']

if __name__ == '__main__':
  app.run()

